<?php
$this->headLink()->prependStylesheet($this->assetUrl('css/browse-preview.css'));
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
?>
<div class="preview-block">

<?php if ($this->heading): ?>
<h2><?php echo $escape($this->heading); ?></h2>
<?php endif; ?>

<ul class="resource-list preview">
<?php
$showThumbnail = in_array('thumbnail', $this->components);
$showHeading = in_array('resource-heading', $this->components);
$showBody = in_array('resource-body', $this->components);
$headingTerm = $this->siteSetting('browse_heading_property_term');
$bodyTerm = $this->siteSetting('browse_body_property_term');

foreach ($this->resources as $resource):
    $heading = $headingTerm ? $resource->value($headingTerm, ['default' => $translate('[Untitled]')]) : $resource->displayTitle();
    $body = $bodyTerm ? $resource->value($bodyTerm) : $resource->displayDescription();
?>
    <li class="<?php echo $this->resourceType; ?> resource">
        <?php
        if ($showThumbnail):
          echo $resource->linkRaw($this->thumbnail($resource, 'square', ['title' => $heading]), null, ['class' => 'resource-thumbnail']);
        ?>
            <h3><?=$resource->link($heading, null, ['class' => 'resource-title']);?></h3>
        <?php 
        else:?> 
            <h3 class="no-img"><?=$resource->link($heading, null, ['class' => 'resource-title']);?></h3>
        <?php
          endif;?>
    </li>
<?php endforeach; ?>
    <li class="browse-all">
<?php
    
if ($this->linkText):
    echo $this->hyperlink($this->linkText, $this->url(
        'site/resource', ['controller' => $this->resourceType, 'action' => 'browse'], ['query' => $this->query], true
    ));
endif;
?>
</li>
</ul>


</div>
