<style>
.sqiles {
display: flex;
flex-wrap: wrap;

}
.sqile {
--sqile-width: 200px;
aspect-ratio: 1 / 1;
width: var(--sqile-width);

  display: flex;
  flex-direction: column;
  justify-content: end;
  align-items: center;
  position: relative;

  background-position: center;
  background-size: cover;
  background-repeat: no-repeat;

  box-shadow: 0 0 5px 5px color-mix(in oklab, var(--midphire) 10%, transparent);
  border: 1px solid var(--fg-color);
  overflow: hidden;

  transition: 250ms;

  &:hover {
    box-shadow: 0 0 5px 5px color-mix(in oklab, var(--midphire) 20%, transparent);
  & .sqitle {
    opacity: 0.9999;
}
  }
& .sqitle {
  position: absolute;
top: 0;
right: 0;
bottom: 0;
left: 0;
z-index: 2;
opacity: 0.0001;
background: var(--bg-color-2);
color: var(--fg-color-2);


  display: flex;
  justify-content: center;
  align-items: center;
text-align: center;
  transition: 250ms;
}
}

</style>
<?php foreach ($subjectValues as $values): ?>
        <?php foreach ($values as $value): ?>
<?php 
    $resource = $value["val"]->resource();
      $resource->scriptoItem = $this->api()->searchOne('scripto_items', ['item_id' => $resource->id()])->getContent();
      if ($resource->scriptoItem) {
        $resource->mediaCount = $resource->scriptoItem->mediaCount();
        $resource->approvedMediaCount = $resource->scriptoItem->isApprovedMediaCount();
        /*$resource->percentApproved = 47;*/
        $resource->percentApproved = round(($resource->approvedMediaCount / $resource->mediaCount) * 100);
      } else {
        $resource->mediaCount = 0;
        $resource->approvedMediaCount = 0;
        /*$resource->percentApproved = 47;*/
        $resource->percentApproved = 0;
      }

      $tileData = [
        "tileType" => "manuscript",
        "title" => $resource->displayTitle(),
        "linkUrl" => "/dohmekas/s/transcribe/item/{$resource->id()}",
        "imageUrl" => $thumbnailUrl = $resource->primaryMedia() ? $resource->primaryMedia()->thumbnailUrl('square') : $resource->thumbnailDisplayUrls()["square"],
        "progress" => $resource->percentApproved,
        "detail" => $resource->value("dcterms:abstract"),
        "desc" => $resource->value("dcterms:description"),
        "dates" => $resource->value("dcterms:date"),
        "featured" => false,
      ];

      /*if (true) {*/
        /*echo '<script>console.log("<?= json_encode($value['val']->resource()) ?>)</script>";*/
      /*}*/
      /*echo $this->TileComponent($tileData);*/
      echo $this->SquareTileComponent($tileData);
?>
        <?php endforeach; ?>

<?php endforeach; ?>
