<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');


?>
<div class="preview-block">

<ul class="resource-list preview">
<a href="#" class="link-tile">
<?php echo $escape($this->heading); ?>
</a>
<?php

// percent complete
/* $mediaCount = $scriptoItem->mediaCount(); */
/* $approvedMediaCount = $scriptoItem->isApprovedMediaCount(); */
/* $percentApproved = round(($approvedMediaCount / $mediaCount) * 100); */

$showThumbnail = in_array('thumbnail', $this->components);
$showHeading = in_array('resource-heading', $this->components);
$showBody = in_array('resource-body', $this->components);
$headingTerm = $this->siteSetting('browse_heading_property_term');
$bodyTerm = $this->siteSetting('browse_body_property_term');
foreach ($this->resources as $resource):
    $heading = $headingTerm ? $resource->value($headingTerm, ['default' => $translate('[Untitled]')]) : $resource->displayTitle();
    $body = $bodyTerm ? $resource->value($bodyTerm) : $resource->displayDescription();
    // jimsafley https://forum.omeka.org/t/scripto-item-completion/22548/3 
    $scriptoItem = $this->api()->searchOne('scripto_items', ['item_id' => $resource->id()])->getContent();

    if ($scriptoItem !== null && method_exists($scriptoItem, 'mediaCount') && method_exists($scriptoItem, 'isApprovedMediaCount')) {

      $mediaCount = $scriptoItem->mediaCount();
      $approvedMediaCount = $scriptoItem->isApprovedMediaCount();
      $percentApproved = round(($approvedMediaCount / $mediaCount) * 100);
    } else {
      $percentApproved = 0;
    }
?>

    <li class="card <?php echo $this->resourceType; ?> resource" >
        <div class="resource-meta">
            <div 
              class="progress-bar" 
              style="background-image: 
                linear-gradient(to right, 
                  var(--fg-color) 0%, 
                  var(--fg-color) <?= $percentApproved ?>%, 
                  var(--bg-color) <?= $percentApproved ?>%, 
                  var(--bg-color) 100%
                );">
                  <?php echo $percentApproved ?>% Complete
            </div>
            <?php
            if ($showHeading):
                echo $resource->link($heading, null, ['class' => 'resource-title']); 
            endif; ?>
            <?php if ($showBody && $body): ?>
            <div class="description"><?php echo $escape($body); ?></div>
            <?php endif; ?>
        </div>
        <?php
        if ($showThumbnail):
            echo $resource->linkRaw($this->thumbnail($resource, 'square', ['title' => $heading]), null, ['class' => 'resource-thumbnail']);
        endif;?>
    </li>
<?php endforeach; ?>

<?php
if ($this->linkText):
    echo $this->hyperlink($this->linkText, $this->url(
        'site/resource', ['controller' => $this->resourceType, 'action' => 'browse'], ['query' => $this->query ], true
    ), ['class' => 'link-tile'] );
endif;
?>
</ul>


</div>

