<footer>
  <a href="https://www.newberry.org">The Newberry Library</a>
  <a href="https://www.contactus.org">Contact Us</a>
</footer>
<style>
  footer {
    position: absolute;
    bottom: 0;
    left: 0;
    right: 0;
    /*z-index: ;*/
    padding: 0;
    display: flex;
    justify-content: center;
    align-items: center;
    gap:0;
    text-align: center;
    & a {
      font-family: "styrene";
      padding: 0.5rem 1rem;
      &:first-child {
        border-right: 1px solid var(--fg-color);
      }
    }
  }
</style>
