<?php
$this->scripto()->prepareSiteContext();
$title = $this->scripto()->publicAppTitle();

$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($title);
$this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=Source+Code+Pro|Lato:400,400italic,700,700italic');
$this->headLink()->appendStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headLink()->appendStylesheet($this->assetUrl('vendor/tablesaw/tablesaw.stackonly.css', 'Omeka'));
$this->headLink()->appendStylesheet($this->scripto()->publicAppStylesheet());
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->headScript()->appendFile($this->assetUrl('vendor/tablesaw/tablesaw.stackonly.jquery.js', 'Omeka'));
$this->headScript()->appendFile($this->assetUrl('js/scripto.js', 'Scripto'));
$this->headScript()->appendFile($this->assetUrl('js/public-app.js', 'Scripto'));
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html')->setAttribute('lang', $this->lang()); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
    </head>

    <body>
        <main id="content" class="page-content" aria-label="<?php echo $this->escapeHtml($this->translate('Content')); ?>">
            <div class="wrapper">
                <?php echo $this->messages(); ?>
                <article class="post">
                        <?php echo $this->content; ?>
                </article>
            </div>
        </main>
        <?php include ('header.phtml'); ?>
        <?php include ('footer.phtml'); ?>
    </body>
</html>
