<!-- suppress filter "class" and suppress the whole search filter element if the only filter present is "class" -->
<?php $escape = $this->plugin('escapeHtml'); ?>
<?php if (count($filters) > 0 || ( $filters[0]->filterLabel === "Class" && count($filters) > 1)): ?>

<div class="search-filters">
    <?php foreach ($filters as $filterLabel => $filterValues): ?>
<?php if ($filterLabel !== "Class"): ?>
    <div class="filter">
        <span class="filter-label"><?php echo $escape($filterLabel); ?></span>
        <?php foreach ($filterValues as $filterValue): ?>
        <span class="filter-value"><?php echo $escape($filterValue); ?></span>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
    <?php endforeach; ?>
</div>
<?php endif; ?>
